# My Module
Describe the purpose of your API module here

## Single Resource [/module/{id}]
This resource represents one particular resource identified by its *id*.

+ Parameters

	+ id: `123` (number, required) - The resource id

### Retrieve Resource [GET]

+ Response 200 (application/json)

		{
			"success": true,
			"result": {
				"id": 1,
				"name": "My Widget"
			}
		}

